app:
  nomeArquivo: 'ITAUICONTA_07092020.csv'
  diretorioArquivo: '/home/thiagoalessandro/develop/thiago/gerencia-conta-pagar/importacao/'
  email:
    from: monitora.olx@gmail.com
  log:
    level: ${LOG_LEVEL}
spring:
  mail:
    host: xxxx
    password: xxxx
    port: 587
    username: ${app.email.from}
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          starttls:
            enable: true
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: ${SHOW_SQL}
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  flyway:
    enabled: true
    baseline-on-migrate: true
# logging
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:%wEx}"
  level:
    root: ${app.log.level}
    br:
      com:
        intelector:
          gerenciarcontapagar: ${app.log.level}
    org:
      hibernate:
        type: ${app.log.level}
server:
  servlet:
    context-path: /contaspagar
